# Generated by Django 5.2.7 on 2025-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeepZoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название изображения (например, Mars Crater)', max_length=255, unique=True)),
                ('dzi_path', models.FilePathField(match='.*\\.dzi$', max_length=500, path='media/tiles', recursive=True)),
                ('base_dir', models.FilePathField(match='.*_files$', max_length=500, path='media/tiles', recursive=True)),
                ('width', models.PositiveIntegerField(help_text='Ширина исходного изображения в пикселях')),
                ('height', models.PositiveIntegerField(help_text='Высота исходного изображения в пикселях')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
