# Generated by Django 5.2.7 on 2025-10-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deepzoomimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Высота исходного изображения в пикселях', null=True),
        ),
        migrations.AlterField(
            model_name='deepzoomimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина исходного изображения в пикселях', null=True),
        ),
    ]
